apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-ingestion-ingress
  namespace: health-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /node(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: node-ingestion
                port:
                  number: 3000
